// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpeDjvJBPnYfvtdBDHft6zr8Jf8TSSPSM',
    appId: '1:968195919637:web:077005997fc2b6f691631c',
    messagingSenderId: '968195919637',
    projectId: 'fuckpaha',
    authDomain: 'fuckpaha.firebaseapp.com',
    storageBucket: 'fuckpaha.appspot.com',
    measurementId: 'G-WC8XZ7MB1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtUOEqJyIcaXFyP_Wk2bRXBC25O5K9EXs',
    appId: '1:968195919637:android:154ab7ff2c052dba91631c',
    messagingSenderId: '968195919637',
    projectId: 'fuckpaha',
    storageBucket: 'fuckpaha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjm_O1sHJ-i0SCFyRdyNFlRFx9OXNTx0c',
    appId: '1:968195919637:ios:6093534ecd6eafe291631c',
    messagingSenderId: '968195919637',
    projectId: 'fuckpaha',
    storageBucket: 'fuckpaha.appspot.com',
    iosClientId: '968195919637-3ld6f6ul2b50ba4mr8u1k9t0rphc5gdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjm_O1sHJ-i0SCFyRdyNFlRFx9OXNTx0c',
    appId: '1:968195919637:ios:6093534ecd6eafe291631c',
    messagingSenderId: '968195919637',
    projectId: 'fuckpaha',
    storageBucket: 'fuckpaha.appspot.com',
    iosClientId: '968195919637-3ld6f6ul2b50ba4mr8u1k9t0rphc5gdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseflutter',
  );
}
